routes/web.php
<?php

/**
 * Landing Page Routes
 */
Route::get('/', function () {
    return view('welcome');
});
/**
 * Authentication Routes
 */
Auth::routes();
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('loginAdmin');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');

/**
 * User and Doctor Routes with Auth Middleware (Require Authentication)
 */
Route::group(['middleware' => 'auth'], function() {

	/**
	 * Home Routes
	 */
	// Route::view('/home', 'home');
	Route::view('/doctor', 'Doctor.index');
	Route::view('/user', 'Doctor.index');
	
});

/**
 * Admin Routes with Auth Middleware (Require Authentication)
 */
Route::group(['middleware' => 'auth:admin'], function() {
	Route::view('/admin', 'admin.index');
	Route::resource('admin/admins','Admin\Admins\AdminController' );
Route::resource('admin/users','Admin\Users\UserController');
});
// Route::resource('userRegister','user\UserRegisterController');

Route::resource('advices','Advices\AdvicesController');
Route::resource('illness','Illness\IllnessController');

app/Http/Controllers/Advices/AdviceRochtaController.php
<?php

namespace App\Http\Controllers\Advices;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Advice;
use App\Model\Rochta;


class AdviceRochtaController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->ajax()){
            $rochta = Rochta::find($rochta_id);
            $advices= $rochta-> advices()->attach($advice_id);
            return response($advices); 
    }
}
  
  

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $rochta = Rochta::find($rochta_id);
        $advices= $rochta-> advices()->detach($advice_id);
        return response()->json([
            'success' => 'Record deleted successfully!'
        ]);
    }
}

app/Http/Controllers/Advices/AdvicesController.php
<?php

namespace App\Http\Controllers\Advices;
use App\Model\Advice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Redirect,Response;
// use App\Http\Requests\AdvicesRequest;

class AdvicesController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        //
      $advices =Advice::latest()->paginate(5);
      return view('advices.index',compact('advices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        // return view('Advices.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->ajax()){
        $advices = Advice::create($request->all());
        return response($advices); 
            
    }
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $advice = Advice::findOrFail($id);

        return view('Advices.show',compact('advice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request  $request, $id)
    {
        
        if($request->ajax()){
            $advice = Advice::findOrFail($id);
 
            return Response::json($advice);
   
        }
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        if($request->ajax()){
      
            $advice = Advice::find($id);
           $advice= $advice->update($request->all());
       
            return response($advice); 
           
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // if($request->ajax()){
            
        //    advice::destroy($request->id);

        // return response()->json(['message'=>'advice deleted successfully']);}
        Advice::find($id)->delete($id);
  
        return response()->json([
            'success' => 'Record deleted successfully!'
        ]);
            
   
}
}

resources/views/advices/create.blade.php
<div class="modal fade" id="addFormModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Register New advice</h4>
        </div>
       
       
        <form id="insert" method="POST" action="{{ route('advices.store') }}" >
        
                        @csrf
                        @include('errors')
                        <div class="modal-body">
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Advice</label>

                            <div class="col-md-6">
                                <input id="advice" type="text" class="form-control" name="advice" " required autofocus>

                                @if ($errors->has('advice'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('advice') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button  id="Add" type="submit" class="btn btn-default" >Add</button>
        </div>
        </form>
      </div>
      
    </div>
  </div>
  

resources/views/advices/delete.blade.php
<div id="deleteFormModal" class="modal fade in" >
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<div class="icon-box">
					<i class="material-icons"></i>
				</div>				
				<h4 class="modal-title">Are you sure?</h4>	
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			</div>
			<div class="modal-body">
				<p>Do you really want to delete these records? This process cannot be undone.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
				<button type="button"  id="delete" class="btn btn-danger">Delete</button>
			</div>
		</div>
	</div>
</div>

resources/views/advices/edit.blade.php
<div class="modal fade" id="editFormModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Register New Admin</h4>
        </div>
       
       
        <form id="edit" method="post" action="{{ route('advices.update',$advice->id) }}">
        @csrf
   @method('PATCH')
                        <div class="modal-body">
                        <div class="form-group row">
                            <label for="advice" class="col-md-4 col-form-label text-md-right">Advice</label>

                            <div class="col-md-6">
                                <input id="advice" type="text" class="form-control" name="advice" " required autofocus>

                                @if ($errors->has('advice'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('advice') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id=update  type="submit" class="btn btn-default" >Update</button>
          
        </div>
        </form>
      </div>
      
    </div>
  </div>
  

resources/views/advices/index.blade.php
@extends('dashboard.app')
@section('page-title')
Current Advicesss
@endsection

@section('content')
<div class="container">
<h2>user Dashboard</h2>
  <!-- Trigger the modal with a button -->
  <div>
  <button type="button" class="btn btn-info btn-lg" id="showAddModal">Add New Illness</button>
  </div>
  <div >
  <table class="table table-striped table-hover">
                <thead>
                    <tr>
                    <th>Id</th>
                        <th>ِِِِِِAdvice</th>
                        <th>ACTIONS</th>
                    </tr>
                </thead>
                <tbody id="ajaxTable" >
            
                    @foreach($advices as $advice)
                    <tr id="tr{{$advice->id}}" >
                   
                    <td> {{$advice->id}}</td>
                        <td> {{$advice->advice}}</td>
                       
                        <td>
                        <button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="{{$advice->id}}">Edit</button>
                        <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="{{$advice->id}}">Delete</button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
            <div class="clearfix">
                <div class="hint-text">Showing <b>{{$advices->count()}}</b> out of <b>{{$advices->total()}}</b> entries</div>
                {{ $advices->links() }}
            </div>
            </div>
@include('advices.create')
@include('advices.delete')
@include('advices.edit')
</div>




@endsection

@section('css')
<style>
.divider-text {
    position: relative;
    text-align: center;
    margin-top: 15px;
    margin-bottom: 15px;
}
.divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;   
    z-index: 2;
}
.divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
}
</style>
@endsection

@section('js')
<script>
$(document).ready(function(){
  $("#showAddModal").click(function(){
    $("#addFormModal").modal("show");
  });
  

  $('#insert').on('submit',function (event) {
    event.preventDefault();
    var data=$(this).serialize();
    var url=$(this).attr('action');
    var method=$(this).attr('method');
   $.ajax({
     url:url,
     method:method,
     dataTy: 'json',
     data:data,     
     success:function(data){
       var tr=$('<tr/>');
       tr.prepend($("<td/>",{html :'<button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="'+data.id+'">Edit</button>'+
       ' <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="'+data.id+'">Delete</button>'}))
       .prepend($("<td/>",{text:data.id}))
      .prepend($("<td/>",{text:data.advice}))
      $("#ajaxTable").prepend(tr);
       $('#addFormModal').modal('hide');
     },
     error: function (data) {
   $('#showErrorModal').html('');
   $.each(data.responseJSON.errors, function(key,error) {
     $('#showErrorModal').append('<div class="alert alert-danger">'+error+'</div');
 }); 
},

   });      
  });
  $(document).on('click','#showDeleteModal',function(){
    $('#deleteFormModal').modal('show');
   
    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");
    $('#delete').click(function(){
    $.ajax(
    {
        url: "advices/"+id,
        type: 'DELETE',
        data: {
            "id": id,
            "_token": token,
        },
        success: function (){
         $('#tr'+id).remove();     
        }
    });
    $('#deleteFormModal').modal('hide');   
   
});
});
///////////////edit////////////////
$('body').delegate('#showEditModal', 'click', function(){

    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");
  
        alert(id)
      
     
        $.ajax({
            url:"advices/"+id+"/edit",
            method:'get',
            data:{id:id,
                "_token": token
                },
            dataType:'json',
            success:function(data)
            { $('#edit').find('#name').val(data.advice);
         
  
                $('#editFormModal').modal('show');
            }
        })
    });
    ////////////////////update//////////////////

    $('#edit').on('submit',function (e) {
    e.preventDefault();
    var data=$(this).serialize();
    var url=$(this).attr('action');
    var method=$(this).attr('method');
   $.ajax({
     url:url,
     method:method,
     dataTy: 'json',
     data:data,     
     success:function(data){
         
       var tr=$('<tr/>');
       tr.prepend($("<td/>",{html :'<button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="'+data.id+'">Edit</button>'+
       ' <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="'+data.id+'">Delete</button>'}))
       .prepend($("<td/>",{text:data.id}))
       .prepend($("<td/>",{text:data.advice}))
      $("#tr"+data.id).replaceWith(tr);
       $('#editFormModal').modal('hide');
     },
     error: function (data) {
   $('#showErrorModal').html('');
   $.each(data.responseJSON.errors, function(key,error) {
     $('#showErrorModal').append('<div class="alert alert-danger">'+error+'</div');
 }); 
}

   });      
  });
    
});
</script>
@endsection