routes/web.php
<?php

/**
 * Landing Page Routes
 */
Route::get('/', function () {
    return view('welcome');
});
/**
 * Authentication Routes
 */
Auth::routes();
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('loginAdmin');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');

/**
 * User and Doctor Routes with Auth Middleware (Require Authentication)
 */
Route::group(['middleware' => 'auth'], function() {

	/**
	 * Home Routes
	 */
	// Route::view('/home', 'home');
	Route::view('/doctor', 'Doctor.index');
	Route::view('/user', 'Doctor.index');
	
});

/**
 * Admin Routes with Auth Middleware (Require Authentication)
 */
Route::group(['middleware' => 'auth:admin'], function() {
	Route::view('/admin', 'admin.index');
	Route::resource('admin/admins','Admin\Admins\AdminController' );
Route::resource('admin/users','Admin\Users\UserController');
});
// Route::resource('userRegister','user\UserRegisterController');

Route::resource('advices','Advices\AdvicesController');
Route::resource('illness','Illness\IllnessController');

resources/views/Admin/admins/create.blade.php
<div class="modal fade" id="addFormModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Register New Admin</h4>
        </div>
       
       
        <form id="insert" method="POST" action="{{ route('admins.store') }}" >
        
                        @csrf
                        @include('errors')
                        <div class="modal-body">
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" " required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" " required autofocus>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="type" class="col-md-4 col-form-label text-md-right">Type</label>

                        <div class="col-md-6">
                        <select id="type" name="type" class="form-control">
                        <option value="normal">Normal Admin</option>
                        <option value="super">Super Admin</option>
                        </select>

                                @if ($errors->has('type'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password_confirmation" class="col-md-4 col-form-label text-md-right">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password_confirmation" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>
                     

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button  id="Add" type="submit" class="btn btn-default" >Add</button>
        </div>
        </form>
      </div>
      
    </div>
  </div>
  

resources/views/Admin/admins/delete.blade.php
<div id="deleteFormModal" class="modal fade in" >
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<div class="icon-box">
					<i class="material-icons"></i>
				</div>				
				<h4 class="modal-title">Are you sure?</h4>	
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			</div>
			<div class="modal-body">
				<p>Do you really want to delete these records? This process cannot be undone.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
				<button type="button"  id="delete" class="btn btn-danger">Delete</button>
			</div>
		</div>
	</div>
</div>

resources/views/Admin/admins/edit.blade.php
<div class="modal fade" id="editFormModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Register New Admin</h4>
        </div>
       
       
        <form id="edit" method="post" action="{{ route('admins.update',$admin->id) }}">
        @csrf
   @method('PATCH')
                        <div class="modal-body">
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" " required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" " required autofocus>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="type" class="col-md-4 col-form-label text-md-right">Type</label>

                        <div class="col-md-6">
                        <select id="type" name="type" class="form-control">
                        <option value="normal">Normal Admin</option>
                        <option value="super">Super Admin</option>
                        </select>

                                @if ($errors->has('type'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id=update  type="submit" class="btn btn-default" >Update</button>
          
        </div>
        </form>
      </div>
      
    </div>
  </div>
  

resources/views/Admin/admins/index.blade.php
@extends('dashboard.app')
@section('page-title')
Current Admins
@endsection

@section('content')
<div class="container">
<h2>Admin Dashboard</h2>
  <!-- Trigger the modal with a button -->
  <div>
  <button type="button" class="btn btn-info btn-lg" id="showAddModal">Add New Admin</button>
  </div>
  <div >
  <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NAME</th>
                        <th>type </th>
                        <th>EMAIL </th>
                        <th>UPDATED AT</th>
                        <th>ACTIONS</th>
                    </tr>
                </thead>
                <tbody id="ajaxTable" >
                @php $i = 0 @endphp
                    @foreach($admins as $admin)
                    @php $i++ @endphp
                    <tr id="tr{{$admin->id}}" >
                   
                        <td> {{$admin->id}}</td>
                        <td>{{$admin->name}}</td>
                        <td>{{$admin->type}}</td>
                        <td>{{$admin->email}}</td>
                        <td>{{$admin->updated_at}}</td>
                        
                        <td>
                        <button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="{{$admin->id}}">Edit</button>
                        <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="{{$admin->id}}">Delete</button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
            <div class="clearfix">
                <div class="hint-text">Showing <b>{{$admins->count()}}</b> out of <b>{{$admins->total()}}</b> entries</div>
                {{ $admins->links() }}
            </div>
            </div>
@include('admin.admins.create')
@include('admin.admins.delete')
@include('admin.admins.edit')
</div>




@endsection

@section('css')
<style>
.divider-text {
    position: relative;
    text-align: center;
    margin-top: 15px;
    margin-bottom: 15px;
}
.divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;   
    z-index: 2;
}
.divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
}
</style>
@endsection

@section('js')
<script>
$(document).ready(function(){
  $("#showAddModal").click(function(){
    $("#addFormModal").modal("show");
  });
  

  $('#insert').on('submit',function (event) {
    event.preventDefault();
    var data=$(this).serialize();
    var url=$(this).attr('action');
    var method=$(this).attr('method');
   $.ajax({
     url:url,
     method:method,
     dataTy: 'json',
     data:data,     
     success:function(data){
       var tr=$('<tr/>');
       tr.prepend($("<td/>",{html :'<button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="'+data.id+'">Edit</button>'+
       ' <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="'+data.id+'">Delete</button>'}))
      .prepend($("<td/>",{text:data.updated_at})).prepend($("<td/>",{text:data.email}))
       .prepend($("<td/>",{text:data.type}))
       .prepend($("<td/>",{text:data.name}))
       .prepend($("<td/>",{text:data.id}))
      $("#ajaxTable").prepend(tr);
       $('#addFormModal').modal('hide');
     },
     error: function (data) {
   $('#showErrorModal').html('');
   $.each(data.responseJSON.errors, function(key,error) {
     $('#showErrorModal').append('<div class="alert alert-danger">'+error+'</div');
 }); 
},

   });      
  });
  $(document).on('click','#showDeleteModal',function(){
    $('#deleteFormModal').modal('show');
   
    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");
    $('#delete').click(function(){
    $.ajax(
    {
        url: "admins/"+id,
        type: 'DELETE',
        data: {
            "id": id,
            "_token": token,
        },
        success: function (){
         $('#tr'+id).remove();     
        }
    });
    $('#deleteFormModal').modal('hide');   
   
});
});
///////////////edit////////////////
$('body').delegate('#showEditModal', 'click', function(){

    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");
  
        alert(id)
      
     
        $.ajax({
            url:"admins/"+id+"/edit",
            method:'get',
            data:{id:id,
                "_token": token
                },
            dataType:'json',
            success:function(data)
            { $('#edit').find('#name').val(data.name);
            $('#edit').find('#email').val(data.email);
            $('#edit').find('#type').val(data.type);
                $('#editFormModal').modal('show');
            }
        })
    });
    ////////////////////update//////////////////


    

    $('#edit').on('submit',function (e) {
    e.preventDefault();
    var data=$(this).serialize();
    var url=$(this).attr('action');
    var method=$(this).attr('method');
    alert(data)
console.log(data)
   $.ajax({
     url:url,
     method:method,
     dataTy: 'json',
     data:data,     
     success:function(data){
         
       var tr=$('<tr/>');
       tr.prepend($("<td/>",{html :'<button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="'+data.id+'">Edit</button>'+
       ' <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="'+data.id+'">Delete</button>'}))
      .prepend($("<td/>",{text:data.updated_at})).prepend($("<td/>",{text:data.email}))
       .prepend($("<td/>",{text:data.type}))
       .prepend($("<td/>",{text:data.name}))
       .prepend($("<td/>",{text:data.id}))
      $("#ajaxTable"+data.id).replaceWith(tr);
       $('#editFormModal').modal('hide');
     },
     error: function (data) {
   $('#showErrorModal').html('');
   $.each(data.responseJSON.errors, function(key,error) {
     $('#showErrorModal').append('<div class="alert alert-danger">'+error+'</div');
 }); 
},

   });      
  });
});
</script>
@endsection