routes/web.php
<?php

/**
 * Landing Page Routes
 */
Route::get('/', function () {
    return view('welcome');
});
/**
 * Authentication Routes
 */
Auth::routes();
Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm')->name('loginAdmin');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');

/**
 * User and Doctor Routes with Auth Middleware (Require Authentication)
 */
Route::group(['middleware' => 'auth'], function() {

	/**
	 * Home Routes
	 */
	// Route::view('/home', 'home');
	Route::view('/doctor', 'Doctor.index');
	Route::view('/user', 'Doctor.index');
	
});

/**
 * Admin Routes with Auth Middleware (Require Authentication)
 */
Route::group(['middleware' => 'auth:admin'], function() {
	Route::view('/admin', 'admin.index');
	Route::resource('admin/admins','Admin\Admins\AdminController' );
Route::resource('admin/users','Admin\Users\UserController');
});
// Route::resource('userRegister','user\UserRegisterController');

Route::resource('advices','Advices\AdvicesController');
Route::resource('illness','Illness\IllnessController');

app/Http/Controllers/Illness/IllnessController.php
<?php

namespace App\Http\Controllers\Illness;
use App\Model\Illness;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Redirect,Response;
// use App\Http\Requests\IllnessRequest;

class IllnessController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        //
      $illness =Illness::latest()->paginate(5);
      return view('illness.index',compact('illness'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        // return view('illness.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->ajax()){
        $illness = Illness::create($request->all());
        return response($illness); 
            
    }
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $illness = Illness::findOrFail($id);

        return view('illness.show',compact('illness'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request  $request, $id)
    {
        
        if($request->ajax()){
            $illness = Illness::findOrFail($id);
 
            return Response::json($illness);
   
        }
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        if($request->ajax()){
      
            $illness = Illness::find($id);
           $illness= $illness->update($request->all());
       
            return response($illness); 
           
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // if($request->ajax()){
            
        //    illness::destroy($request->id);

        // return response()->json(['message'=>'illness deleted successfully']);}
        Illness::find($id)->delete($id);
  
        return response()->json([
            'success' => 'Record deleted successfully!'
        ]);
            
   
}
}

app/Http/Controllers/Illness/IllnessDrugController.php
<?php

namespace App\Http\Controllers\Illness;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IllnessDrugController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if($request->ajax()){
            $illness = Illness::find($illness_id);
            $drug= $illness-> drugs()->attach($illness_id);
            return response($drug); 
    }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $illness = Illness::find($illness_id);
        $drug= $illness-> drugs()->detach($illness_id);
        return response()->json([
            'success' => 'Record deleted successfully!'
        ]);
    }
}

resources/views/illness/create.blade.php
<div class="modal fade" id="addFormModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Register New illness</h4>
        </div>
       
       
        <form id="insert" method="POST" action="{{ route('illness.store') }}" >
        
                        @csrf
                        @include('errors')
                        <div class="modal-body">
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">illness name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" " required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control" name="description" " required autofocus>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button  id="Add" type="submit" class="btn btn-default" >Add</button>
        </div>
        </form>
      </div>
      
    </div>
  </div>
  

resources/views/illness/delete.blade.php
<div id="deleteFormModal" class="modal fade in" >
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<div class="icon-box">
					<i class="material-icons"></i>
				</div>				
				<h4 class="modal-title">Are you sure?</h4>	
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			</div>
			<div class="modal-body">
				<p>Do you really want to delete these records? This process cannot be undone.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
				<button type="button"  id="delete" class="btn btn-danger">Delete</button>
			</div>
		</div>
	</div>
</div>

resources/views/illness/edit.blade.php
<div class="modal fade" id="editFormModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Register New Admin</h4>
        </div>
       
       
        <form id="edit" method="post" action="{{ route('illness.update',$illness->id) }}">

        @csrf
   @method('PATCH')
                        <div class="modal-body">
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">illness name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" " required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control" name="description" " required autofocus>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>



        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id=update  type="submit" class="btn btn-default" >Update</button>
          
        </div>
        </form>
      </div>
      
    </div>
  </div>
  

resources/views/illness/index.blade.php
@extends('dashboard.app')
@section('page-title')
Current illnessss
@endsection

@section('content')
<div class="container">
<h2>user Dashboard</h2>
  <!-- Trigger the modal with a button -->
  <div>
  <button type="button" class="btn btn-info btn-lg" id="showAddModal">Add New illness</button>
  </div>
  <div >
  <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>ACTIONS</th>
                    </tr>
                </thead>
                <tbody id="ajaxTable" >
             
                    @foreach($illness as $illness)
                  
                    <tr id="tr{{$illness->id}}" >
                   
                        <td> {{$illness->id}}</td>
                        <td> {{$illness->name}}</td>
                        <td> {{$illness->description}}</td>
                       
                        <td>
                        <button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="{{$illness->id}}">Edit</button>
                        <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="{{$illness->id}}">Delete</button>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
           
            </div>
@include('illness.create')
@include('illness.edit')
@include('illness.delete')

</div>




@endsection

@section('css')
<style>
.divider-text {
    position: relative;
    text-align: center;
    margin-top: 15px;
    margin-bottom: 15px;
}
.divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;   
    z-index: 2;
}
.divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
}
</style>
@endsection

@section('js')
<script>
$(document).ready(function(){
  $("#showAddModal").click(function(){
    $("#addFormModal").modal("show");
  });
  

  $('#insert').on('submit',function (event) {
    event.preventDefault();
    var data=$(this).serialize();
    var url=$(this).attr('action');
    var method=$(this).attr('method');
   $.ajax({
     url:url,
     method:method,
     dataTy: 'json',
     data:data,     
     success:function(data){
       var tr=$('<tr/>');
       tr.prepend($("<td/>",{html :'<button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="'+data.id+'">Edit</button>'+
       ' <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="'+data.id+'">Delete</button>'}))
      .prepend($("<td/>",{text:data.description}))
      .prepend($("<td/>",{text:data.name}))
      .prepend($("<td/>",{text:data.id}))
      $("#ajaxTable").prepend(tr);
       $('#addFormModal').modal('hide');
     },
     error: function (data) {
   $('#showErrorModal').html('');
   $.each(data.responseJSON.errors, function(key,error) {
     $('#showErrorModal').append('<div class="alert alert-danger">'+error+'</div');
 }); 
},

   });      
  });
  $(document).on('click','#showDeleteModal',function(){
    $('#deleteFormModal').modal('show');
   
    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");
    $('#delete').click(function(){
    $.ajax(
    {
        url: "illness/"+id,
        type: 'DELETE',
        data: {
            "id": id,
            "_token": token,
        },
        success: function (){
         $('#tr'+id).remove();     
        }
    });
    $('#deleteFormModal').modal('hide');   
   
});
});
///////////////edit////////////////
$('body').delegate('#showEditModal', 'click', function(){

    var id = $(this).data("id");
    var token = $("meta[name='csrf-token']").attr("content");
  
        alert(id)
      
     
        $.ajax({
            url:"illness/"+id+"/edit",
            method:'get',
            data:{id:id,
                "_token": token
                },
            dataType:'json',
            success:function(data)
            { $('#edit').find('#illness').val(data.id);
         alert(data.id);
  
                $('#editFormModal').modal('show');
            }
        })
    });
    ////////////////////update//////////////////

    $('#edit').on('submit',function (e) {
    e.preventDefault();
    var data=$(this).serialize();
    var url=$(this).attr('action');
    var method=$(this).attr('method');
    alert(data.id);
   $.ajax({
     url:url,
     method:method,
     dataTy: 'json',
     data:data,     
     success:function(data){
         
       var tr=$('<tr/>');
       tr.prepend($("<td/>",{html :'<button type="button" class="btn btn-info btn-lg" id="showEditModal" data-id="'+data.id+'">Edit</button>'+
       ' <button type="button" class="btn btn-info btn-lg" id="showDeleteModal" data-id="'+data.id+'">Delete</button>'}))
       .prepend($("<td/>",{text:data.description}))
      .prepend($("<td/>",{text:data.name}))
      .prepend($("<td/>",{text:data.id}))
      $("#ajaxTable tr#"+data.id).replaceWith(tr);
       $('#editFormModal').modal('hide');
     },
     error: function (data) {
   $('#showErrorModal').html('');
   $.each(data.responseJSON.errors, function(key,error) {
     $('#showErrorModal').append('<div class="alert alert-danger">'+error+'</div');
 }); 
}

   });      
  });
    
});
</script>
@endsection